hi('Boolean',           red)
hi('Character',         green)
hi('ColorColumn',       none,            cursor_line)
hi('Comment',           bright_black,    none,                       'italic')
hi('Conditional',       bright_blue)
hi('Constant',          bright_green)
hi('Cursor',            none,            none,                       'reverse')
hi('CursorColumn',      none,            cursor_line)
hi('CursorLineNr',      black,           bg2,                        'bold')
hi('Debug',             red,             none,                       'bold')
hi('Define',            bright_magenta)
hi('Directory',         blue)
hi('EndOfBuffer',       bg2)
hi('Error',             bright_white,    bright_red,                 'bold')
hi('ErrorMsg',          bright_red,      none,                       'bold')
hi('Exception',         bright_red)
hi('Float',             red)
hi('Folded',            white)
hi('FoldColumn',        none)
hi('Function',          blue)
hi('Identifier',        blue)
hi('Ignore',            bright_black,    none,                       'italic')
hi('IncSearch',         yellow,          bright_yellow,              'bold,underline')
hi('Include',           bright_magenta)
hi('Keyword',           magenta)
hi('Label',             yellow)
hi('LineNr',            fg2)
hi('Macro',             bright_magenta)
hi('MatchParen',        none,            none,                       'bold,underline')
hi('ModeMsg',           white,           bright_blue)
hi('MoreMsg',           blue)
hi('NonText',           fg2)
hi('Normal',            fg,              bg)
hi('Number',            red)
hi('Operator',          none)
hi('Pmenu',             black,           bg3)
hi('PmenuSbar',         none,            bg3)
hi('PmenuSel',          white,           bright_cyan)
hi('PmenuThumb',        none,            black)
hi('PreCondit',         bright_magenta)
hi('PreProc',           bright_magenta)
hi('Question',          blue,            none,                       'bold')
hi('QuickFixLine',      none,            bright_white,               'bold,underline')
hi('Repeat',            bright_blue)
hi('Search',            none,            bright_yellow)
hi('SignColumn',        fg,              none)
hi('Special',           red)
hi('SpecialChar',       red)
hi('SpecialComment',    red)
hi('SpecialKey',        fg2)
hi('SpellBad',          bright_red,      none,                       'undercurl')
hi('SpellCap',          bright_yellow,   none,                       'undercurl')
hi('SpellLocal',        bright_green,    none,                       'undercurl')
hi('SpellRare',         magenta,         none,                       'undercurl')
hi('Statement',         bright_blue)
hi('StatusLine',        black,           bg2,                        'underline')
hi('StatusLineNC',      bright_black,    blend(bg2, 60),             'underline')
hi('StatusLineTerm',    black,           bg2,                        'underline')
hi('StatusLineTermNC',  bright_black,    blend(bg2, 60),             'underline')
hi('StorageClass',      cyan,            none,                       'italic')
hi('String',            green)
hi('Structure',         cyan,            none,                       'italic')
hi('Substitute',        white,           black)
hi('TabLine',           bright_black,    blend(bg2, 60),             'underline')
hi('TabLineFill',       bright_black,    blend(bg2, 60),             'underline')
hi('TabLineSel',        black,           bg2,                        'underline,bold')
hi('Tag',               blue,            none,                       'underline')
hi('Terminal',          fg,              bg)
hi('Title',             blue)
hi('Todo',              none,            bg2,                        'bold,underline')
hi('Type',              cyan,            none,                       'italic')
hi('Typedef',           cyan,            none,                       'italic')
hi('Underlined',        blue,            none,                       'underline')
hi('VertSplit',         bright_black)
hi('Visual',            none,            white)
hi('VisualNOS',         none,            white)
hi('WarningMsg',        yellow,          none,                       'bold,reverse')
hi('WildMenu',          none,            none,                       'reverse')
hi('Whitespace',        fg2)

li('lCursor',           'Cursor')
li('CursorIM',          'Cursor')
li('TermCursor',        'Cursor')
li('CursorLine',        'CursorColumn')
