hi('Boolean', red)
hi('Character', green)
hi('ColorColumn', 'NONE', cursor_line)
hi('Comment', bright_black, 'NONE', 'italic')
hi('Conditional', bright_blue)
hi('Constant', bright_green)
hi('Cursor', 'NONE', 'NONE', 'reverse')
hi('CursorColumn', 'NONE', cursor_line)
hi('CursorLineNr', black, bg2, 'bold')
hi('Debug', red, 'NONE', 'bold')
hi('Define', bright_magenta)
hi('DiffAdd', 'NONE', blend(bg, bright_green, 0.3))
hi('DiffDelete', 'NONE', blend(bg, bright_red, 0.3))
hi('DiffChange', 'NONE', blend(bg, bright_yellow, 0.3))
hi('DiffText', 'NONE', blend(bg, bright_green, 0.3), 'bold')
hi('Directory', blue)
hi('EndOfBuffer', 'bg')
hi('Error', bright_white, bright_red, 'bold')
hi('ErrorMsg', bright_red, 'NONE', 'bold')
hi('Exception', bright_red)
hi('Float', red)
hi('Folded', white)
hi('FoldColumn', 'NONE')
hi('Function', blue)
hi('Identifier', blue)
hi('Ignore', bright_black, 'NONE', 'italic')
hi('IncSearch', yellow, bright_yellow, 'bold,underline')
hi('Include', bright_magenta)
hi('Keyword', magenta)
hi('Label', yellow)
hi('LineNr', fg2)
hi('Macro', bright_magenta)
hi('MatchParen', 'NONE', 'NONE', 'bold,underline')
hi('ModeMsg', white, bright_blue)
hi('MoreMsg', blue)
hi('NonText', fg2)
hi('Normal', fg, bg)
hi('Number', red)
hi('Operator', 'NONE')
hi('Pmenu', black, bg3)
hi('PmenuSbar', 'NONE', bg3)
hi('PmenuSel', white, bright_cyan)
hi('PmenuThumb', 'NONE', black)
hi('PreCondit', bright_magenta)
hi('PreProc', bright_magenta)
hi('Question', blue, 'NONE', 'bold')
hi('QuickFixLine', 'NONE', bright_white, 'bold,underline')
hi('Repeat', bright_blue)
hi('Search', 'NONE', bright_yellow)
hi('SignColumn', fg, 'NONE')
hi('Special', red)
hi('SpecialChar', red)
hi('SpecialComment', red)
hi('SpecialKey', fg2)
hi('SpellBad', bright_red, 'NONE', 'undercurl')
hi('SpellCap', bright_yellow, 'NONE', 'undercurl')
hi('SpellLocal', bright_green, 'NONE', 'undercurl')
hi('SpellRare', magenta, 'NONE', 'undercurl')
hi('Statement', bright_blue)
hi('StatusLine', black, bg2, 'underline')
hi('StatusLineNC', bright_black, blend(bg2, bg, 0.6), 'underline')
hi('StatusLineTerm', black, bg2, 'underline')
hi('StatusLineTermNC', bright_black, blend(bg2, bg, 0.6), 'underline')
hi('StorageClass', cyan, 'NONE', 'italic')
hi('String', green)
hi('Structure', cyan, 'NONE', 'italic')
hi('Substitute', white, black)
hi('TabLine', bright_black, blend(bg2, bg, 0.6), 'underline')
hi('TabLineFill', bright_black, blend(bg2, bg, 0.6), 'underline')
hi('TabLineSel', black, bg2, 'underline,bold')
hi('Tag', blue, 'NONE', 'underline')
hi('Terminal', fg, bg)
hi('Title', red)
hi('Todo', 'NONE', bg2, 'bold,underline')
hi('Type', cyan, 'NONE', 'italic')
hi('Typedef', cyan, 'NONE', 'italic')
hi('Underlined', blue, 'NONE', 'underline')
hi('VertSplit', bright_black)
hi('Visual', 'NONE', white)
hi('VisualNOS', 'NONE', white)
hi('WarningMsg', yellow, 'NONE', 'bold,reverse')
hi('WildMenu', 'NONE', 'NONE', 'reverse')
hi('Whitespace', fg2)
-- hi! link lCursor Cursor
-- hi! link CursorIM Cursor
-- hi! link TermCursor Cursor
-- hi! link CursorLine CursorColumn

