-- Lsp
hi('LspDiagnosticsError',               blend(bright_red, 60),      none,                        'undercurl,italic')
hi('LspDiagnosticsErrorSign',           bright_red,                 blend(red, 90),              'bold,italic')
hi('LspDiagnosticsErrorFloating',       bright_red)
hi('LspDiagnosticsWarning',             blend(yellow, 40),          none,                        'undercurl,italic')
hi('LspDiagnosticsWarningSign',         yellow,                     blend(yellow, 90),           'italic')
hi('LspDiagnosticsWarningFloating',     yellow)
hi('LspDiagnosticsInformation',         blend(bright_blue, 30),     none,                        'italic')
hi('LspDiagnosticsInformationSign',     bright_blue,                blend(bright_blue, 90),      'italic')
hi('LspDiagnosticsInformationFloating', bright_blue)
hi('LspDiagnosticsHint',                blend(bright_magenta, 50),  none,                        'italic,undercurl')
hi('LspDiagnosticsHintSign',            bright_magenta,             blend(bright_magenta, 92),   'italic,bold')
hi('LspDiagnosticsHintFloating',        bright_magenta)
hi('LspReferenceText',                  none,                       bright_cyan)
hi('LspReferenceRead',                  none,                       bright_cyan)
hi('LspReferenceWrite',                 none,                       bright_cyan)

